import Home from "@/containers/home";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Forcythe - Your Partner in Scalable Business Growth | Digital Solution Expert",
  description: "Generated by create next app",
};

export default function HomePage() {
  return <Home />;
}
